// ─── ENDPOINTS (à brancher plus tard) ────────────────────────────────────────
// GET  /api/boutique/produits                   → liste des produits disponibles
// GET  /api/boutique/produits/:id               → détails d'un produit
// POST /api/boutique/commandes                  → passer une commande
//   Body: { citoyenId, items: [{ produitId, quantite }], adresseLivraison, modePaiement }
// GET  /api/boutique/commandes?citoyenId=:id    → historique des commandes (panier/achats)
// GET  /api/boutique/commandes/:id              → détails d'une commande

// ─── CATÉGORIES ───────────────────────────────────────────────────────────────

export const CATEGORIES = [
  { id: "tous",      label: "Tous",             emoji: "🛒" },
  { id: "plastique", label: "Plastique",         emoji: "♻️" },
  { id: "metal",     label: "Métal / Ferraille", emoji: "🔩" },
  { id: "papier",    label: "Papier / Carton",   emoji: "📦" },
  { id: "verre",     label: "Verre",             emoji: "🍾" },
  { id: "organique", label: "Compost / Organique",emoji: "🌱" },
  { id: "electronique", label: "Électronique",   emoji: "💻" },
  { id: "textile",   label: "Textile",           emoji: "👕" },
  { id: "bois",      label: "Bois",              emoji: "🪵" },
];

// ─── PRODUITS MOCK ────────────────────────────────────────────────────────────

export const produitsMock = [
  {
    id: 1,
    nom: "Granulés plastique HDPE recyclé",
    categorie: "plastique",
    prix: 1200,
    unite: "kg",
    stock: 450,
    vendeur: "Centre Collecte Yaoundé",
    ville: "Yaoundé",
    description: "Granulés de plastique HDPE (polyéthylène haute densité) issus du recyclage de bouteilles et contenants. Idéal pour la fabrication de tuyaux, mobilier urbain et objets moulés.",
    usage: ["Fabrication de tuyaux", "Mobilier de jardin", "Bacs de rangement", "Objets moulés"],
    qualite: "Grade A — trié, lavé, granulé",
    minCommande: 10,
    emoji: "♻️",
    couleur: "bg-blue-50",
    badge: "Populaire",
  },
  {
    id: 2,
    nom: "Ferraille acier mixte",
    categorie: "metal",
    prix: 850,
    unite: "kg",
    stock: 1200,
    vendeur: "Centre Collecte Douala",
    ville: "Douala",
    description: "Ferraille d'acier mixte collectée et triée, composée de profilés, tôles et pièces diverses. Destinée aux fonderies et ateliers de revalorisation métallique.",
    usage: ["Fonderie", "Fabrication de pièces", "Revalorisation métallique"],
    qualite: "Trié, débarrassé des matières non-ferreux",
    minCommande: 50,
    emoji: "🔩",
    couleur: "bg-gray-50",
    badge: null,
  },
  {
    id: 3,
    nom: "Carton ondulé compressé",
    categorie: "papier",
    prix: 300,
    unite: "kg",
    stock: 800,
    vendeur: "Centre Collecte Yaoundé",
    ville: "Yaoundé",
    description: "Carton ondulé compressé en balles de 30 à 50 kg. Collecte auprès de commerces et supermarchés. Parfait pour la production de papier recyclé ou l'emballage.",
    usage: ["Production papier recyclé", "Emballages", "Isolation"],
    qualite: "Sec, propre, sans contaminants",
    minCommande: 30,
    emoji: "📦",
    couleur: "bg-amber-50",
    badge: null,
  },
  {
    id: 4,
    nom: "Calcin verre blanc trié",
    categorie: "verre",
    prix: 180,
    unite: "kg",
    stock: 320,
    vendeur: "Centre Collecte Bafoussam",
    ville: "Bafoussam",
    description: "Calcin de verre blanc issu du tri sélectif. Broyé et calibré, prêt à être réintroduit dans le processus de fabrication verrière.",
    usage: ["Verrerie industrielle", "Fabrication bouteilles", "Matériaux isolants"],
    qualite: "Trié par couleur, broyé, sans impuretés",
    minCommande: 100,
    emoji: "🍾",
    couleur: "bg-cyan-50",
    badge: null,
  },
  {
    id: 5,
    nom: "Compost mûr certifié",
    categorie: "organique",
    prix: 450,
    unite: "kg",
    stock: 600,
    vendeur: "Centre Collecte Yaoundé",
    ville: "Yaoundé",
    description: "Compost mûr produit à partir de déchets organiques ménagers et de marché. Riche en matières organiques, il améliore la structure et la fertilité des sols agricoles et de jardin.",
    usage: ["Agriculture", "Jardinage", "Maraîchage", "Pépinières"],
    qualite: "Maturité complète, pH neutre, sans pathogènes",
    minCommande: 5,
    emoji: "🌱",
    couleur: "bg-green-50",
    badge: "Bio",
  },
  {
    id: 6,
    nom: "Vermiculture — Vers de compost",
    categorie: "organique",
    prix: 8000,
    unite: "lot de 500g",
    stock: 40,
    vendeur: "Centre Collecte Yaoundé",
    ville: "Yaoundé",
    description: "Vers Eisenia fetida (vers rouges) élevés pour la lombricompostage. Idéals pour transformer les déchets organiques en engrais naturel de haute qualité.",
    usage: ["Lombricompostage", "Amendement sol", "Pisciculture"],
    qualite: "Vers sains, actifs, lot de 500g",
    minCommande: 1,
    emoji: "🪱",
    couleur: "bg-green-50",
    badge: "Stock limité",
  },
  {
    id: 7,
    nom: "Composants électroniques triés",
    categorie: "electronique",
    prix: 3500,
    unite: "kg",
    stock: 85,
    vendeur: "Centre Collecte Douala",
    ville: "Douala",
    description: "Lot de composants électroniques issus de DEEE (Déchets d'Équipements Électriques et Électroniques). Contient circuits imprimés, connecteurs et métaux précieux récupérables.",
    usage: ["Extraction métaux précieux", "Reconditionnement", "Recyclage industriel"],
    qualite: "Dépolluants, sans piles ni batteries",
    minCommande: 5,
    emoji: "💻",
    couleur: "bg-purple-50",
    badge: null,
  },
  {
    id: 8,
    nom: "Textile coton trié",
    categorie: "textile",
    prix: 600,
    unite: "kg",
    stock: 200,
    vendeur: "Centre Collecte Douala",
    ville: "Douala",
    description: "Chiffons et textiles en coton triés, lavés et conditionnés. Utilisés pour la fabrication de chiffons d'essuyage industriel ou la production de fibres recyclées.",
    usage: ["Chiffons industriels", "Fibre recyclée", "Isolation"],
    qualite: "Trié par matière, lavé, séché",
    minCommande: 20,
    emoji: "👕",
    couleur: "bg-pink-50",
    badge: null,
  },
  {
    id: 9,
    nom: "Copeaux de bois mélangés",
    categorie: "bois",
    prix: 250,
    unite: "kg",
    stock: 1500,
    vendeur: "Centre Collecte Bafoussam",
    ville: "Bafoussam",
    description: "Copeaux et sciure de bois issus de chantiers et ateliers de menuiserie. Utilisables comme combustible biomasse, litière animale ou mulch de jardin.",
    usage: ["Biomasse / combustible", "Litière animale", "Paillage jardin", "Panneaux agglomérés"],
    qualite: "Sec, sans traitements chimiques",
    minCommande: 50,
    emoji: "🪵",
    couleur: "bg-orange-50",
    badge: null,
  },
];

// ─── COMMANDES MOCK ───────────────────────────────────────────────────────────

export const commandesMock = [
  {
    id: "CMD-2024-001",
    date: "2024-03-18",
    statut: "livrée",
    total: 22500,
    adresseLivraison: "Rue des Palmiers Nr 12, Bastos, Yaoundé",
    modePaiement: "Mobile Money",
    items: [
      { produitId: 1, nom: "Granulés plastique HDPE recyclé", quantite: 15, prixUnitaire: 1200, unite: "kg", emoji: "♻️" },
      { produitId: 5, nom: "Compost mûr certifié",            quantite: 10, prixUnitaire: 450,  unite: "kg", emoji: "🌱" },
    ],
  },
  {
    id: "CMD-2024-002",
    date: "2024-03-20",
    statut: "en_cours",
    total: 17500,
    adresseLivraison: "Rue des Palmiers Nr 12, Bastos, Yaoundé",
    modePaiement: "Mobile Money",
    items: [
      { produitId: 5, nom: "Compost mûr certifié",  quantite: 20, prixUnitaire: 450,  unite: "kg",       emoji: "🌱" },
      { produitId: 6, nom: "Vers de compost",        quantite: 5,  prixUnitaire: 8000, unite: "lot 500g", emoji: "🪱" },
    ],
  },
  {
    id: "CMD-2024-003",
    date: "2024-03-22",
    statut: "confirmée",
    total: 42500,
    adresseLivraison: "Rue des Palmiers Nr 12, Bastos, Yaoundé",
    modePaiement: "Virement bancaire",
    items: [
      { produitId: 2, nom: "Ferraille acier mixte", quantite: 50, prixUnitaire: 850, unite: "kg", emoji: "🔩" },
    ],
  },
];

// ─── STATUTS COMMANDES ────────────────────────────────────────────────────────

export const STATUT_COMMANDE = {
  confirmée:  { label: "Confirmée",   bg: "bg-blue-50",   text: "text-blue-700",  dot: "bg-blue-500",  icon: "✅" },
  en_cours:   { label: "En livraison",bg: "bg-amber-50",  text: "text-amber-700", dot: "bg-amber-500", icon: "🚚" },
  livrée:     { label: "Livrée",      bg: "bg-green-50",  text: "text-green-700", dot: "bg-green-500", icon: "📦" },
  annulée:    { label: "Annulée",     bg: "bg-gray-100",  text: "text-gray-500",  dot: "bg-gray-400",  icon: "❌" },
};
